### PR TITLE
Enable support for multiple source mappings provided.

### PR DESCRIPTION
**Pull request by jlamoree**

### CODE REVIEW

**Comment by jlamoree** [comment]
Any thoughts on this?

**Comment by lmajano** [comment]
Sorry @jlamoree I have been swamped
I will revise

**Comment by bdw429s** [comment]
@lmajano @jlamoree I think we should avoid passing JSON in command parameters.  It's just ungainly in general, hard to type, hard to read, and hard to escape.  For complex settings like this, I would recommend we introduce either a dedicated JSON file, or a key in `box.json` like we do for `testbox run`.  

As an alternative approach, if we want to pass these parameters, it would be best to use this syntax:

```
docbox generate 
    mappings:v1.models="../src/modules_app/v1/models"
    mappings:v2.models="../src/modules_app/v2/models"
```

CommandBox has generic support for parameters in the format of `foo:bar` and it creates a struct out of the first part and a matching key for each bit after the colon.  So the example above would create `arguments.mappings` inside of the command with keys `v1.models` and `v2.models`  which could be iterated over.  

You can read the docs on this here:
https://commandbox.ortusbooks.com/developing-for-commandbox/commands/using-parameters/dynamic-parameters

**Comment by jlamoree** [comment]
I agree. The JSON on the command line is ugly. I was just trying to make the DocBox command do what the source says it does: https://github.com/Ortus-Solutions/commandbox-docbox/commit/cb45ce9c7f9823b78b5322215f54b279ea8ef92f#r29104904

I'll change it to use the dynamic parameters syntax.

**Pull request merged**
